// File: robot_system.proto
//
// Copyright 2026 Bear Robotics, Inc. All rights reserved.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

syntax = "proto3";

package bearrobotics.api.v1.core;

// Robot-level system operation to be executed.
message SystemCommand {
  // User must specify a hard or soft reboot type.
  message Reboot {
    enum Type {
      TYPE_UNKNOWN = 0;

      // Perform an OS-level reboot without powering off hardware devices.
      TYPE_SOFTWARE_ONLY = 1;

      // Perform a full power-cycle including hardware devices.
      TYPE_WITH_HARDWARE = 2;
    }
    Type type = 1;
  }

  // Shuts down the robot system.
  // Pass in an empty Shutdown message to initiate a shutdown.
  message Shutdown {}

  // Client-specified system command to be executed.
  oneof command {
    Reboot reboot = 1;
    Shutdown shutdown = 2;
  }
}

// SystemInfo contains various system-level data of a robot.
message SystemInfo {
  // The distribution version currently installed and running on the robot.
  // e.g. "servi-24.03"
  string software_version = 1;

  // RobotFamily defines the classification or family of the robot.
  enum RobotFamily {
    ROBOT_FAMILY_UNKNOWN = 0;
    ROBOT_FAMILY_SERVI = 1;
    ROBOT_FAMILY_SERVI_MINI = 2;
    ROBOT_FAMILY_SERVI_PLUS = 3;
    ROBOT_FAMILY_SERVI_LIFT = 4;
    ROBOT_FAMILY_CARTI_100 = 5;
    ROBOT_FAMILY_CARTI_600 = 6;
    ROBOT_FAMILY_SERVI_Q = 7;
  }
  RobotFamily robot_family = 2;

  // Unique identifier for the robot. e.g. "pennybot-abc123"
  string robot_id = 3;

  // A user-friendly name for the robot, typically used for display purposes.
  string display_name = 4;
}
