// "Continue with Google" / "Continue with Microsoft". Standard OAuth 2.0
// authorization-code flow, server-side (confidential client with a secret),
// not the SPA/PKCE shape, because this is a server-rendered app with no
// client JavaScript, same reasoning as the rest of site.mjs.
//
// Both providers are wired through the same generic functions below rather
// than two bespoke integrations, because the only real difference between
// "sign in with Google" and "sign in with Microsoft" is which URLs to hit and
// which JSON field holds the email. Everything after that, state handling,
// account creation, session issuance, is identical and already exists in
// auth.mjs; this file's only job is turning a provider's callback into a
// verified email address.
import { randomBytes } from "node:crypto";
import { newToken, tokensEqual } from "./auth.mjs";

export const OAUTH_STATE_COOKIE = "botlien_oauth_state";
export const STATE_TTL_MS = 10 * 60 * 1000; // long enough for a slow consent screen, short enough to not linger

/** Registry of what each provider needs. No secrets live here, only the
 * public shape of each provider's OAuth endpoints and the scope that gets a
 * verified email back. Client id/secret come from secrets.local.json, same
 * pattern as bear/gausium/resend, so a laptop with none of this configured
 * still boots, it just does not show the button. */
export const PROVIDERS = {
  google: {
    id: "google",
    label: "Google",
    authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    userinfoUrl: "https://openidconnect.googleapis.com/v1/userinfo",
    scope: "openid email",
    extraAuthorizeParams: { access_type: "online", prompt: "select_account" },
  },
  microsoft: {
    id: "microsoft",
    label: "Microsoft",
    // The "common" tenant accepts both personal Microsoft accounts (Outlook,
    // Hotmail, live.com) and work/school Entra ID accounts, so one provider
    // covers Outlook and Teams/Office 365 sign-in rather than needing a
    // second integration for "work accounts".
    authorizeUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    userinfoUrl: "https://graph.microsoft.com/oidc/userinfo",
    scope: "openid email profile",
    extraAuthorizeParams: { prompt: "select_account" },
  },
};

/** Only returns providers that actually have credentials. This is the single
 * gate the rest of the app checks, site.mjs shows a button only for a key in
 * this map, gate.mjs's /auth/:provider/start 404s for anything not in it, so
 * there is exactly one place that decides whether a provider is live. */
export function createOAuthProviders({ secrets = {}, env = process.env } = {}) {
  const out = {};
  for (const id of Object.keys(PROVIDERS)) {
    const clientId = env[`BOTLIEN_${id.toUpperCase()}_CLIENT_ID`] ?? secrets[id]?.client_id ?? null;
    const clientSecret = env[`BOTLIEN_${id.toUpperCase()}_CLIENT_SECRET`] ?? secrets[id]?.client_secret ?? null;
    if (!clientId || !clientSecret) continue;
    out[id] = { ...PROVIDERS[id], clientId, clientSecret };
  }
  return out;
}

function redirectUriFor(provider, baseUrl) {
  return `${baseUrl.replace(/\/$/, "")}/auth/${provider.id}/callback`;
}

/** Where to send the browser to start consent. `state` is generated by the
 * caller (the route handler) so it can also be the thing written into the
 * cookie, one value, two jobs, instead of two values that could drift. */
export function buildAuthorizeUrl(provider, { state, baseUrl }) {
  const params = new URLSearchParams({
    client_id: provider.clientId,
    redirect_uri: redirectUriFor(provider, baseUrl),
    response_type: "code",
    scope: provider.scope,
    state,
    ...(provider.extraAuthorizeParams ?? {}),
  });
  return `${provider.authorizeUrl}?${params.toString()}`;
}

/** 32 bytes of CSPRNG, prefixed with the provider id so a state cookie issued
 * for one provider can never be replayed against another's callback even if
 * both somehow shared a cookie jar path. */
export function newState(providerId) {
  return `${providerId}:${randomBytes(32).toString("base64url")}`;
}

/** Short-lived, HttpOnly, provider-agnostic (one cookie slot covers whichever
 * provider is mid-flow, nobody runs two consent screens at once). Scoped to
 * /auth so it never rides along on ordinary /owner requests. */
export function oauthStateCookie(state, { secure = true, maxAgeMs = STATE_TTL_MS } = {}) {
  const bits = [
    `${OAUTH_STATE_COOKIE}=${encodeURIComponent(state)}`,
    "Path=/auth",
    "HttpOnly",
    "SameSite=Lax",
    `Max-Age=${Math.floor(maxAgeMs / 1000)}`,
  ];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}

export function clearOauthStateCookie({ secure = true } = {}) {
  const bits = [`${OAUTH_STATE_COOKIE}=`, "Path=/auth", "HttpOnly", "SameSite=Lax", "Max-Age=0"];
  if (secure) bits.push("Secure");
  return bits.join("; ");
}

/** True only for an exact, constant-time match against the cookie the /start
 * leg set. A missing cookie, a missing query param, or a provider-id mismatch
 * (someone hit google's callback with a state minted for microsoft) all fail
 * the same way: reject, do not guess which one was "probably" right. */
export function validState({ providerId, cookieState, queryState }) {
  if (!cookieState || !queryState) return false;
  if (!cookieState.startsWith(`${providerId}:`)) return false;
  return tokensEqual(cookieState, queryState);
}

/** Exchange the authorization code for an access token. Returned shape is
 * {ok:false, error} on any failure rather than a throw, matching mailer.mjs,
 * so a route handler always has a designed screen to show instead of a 500. */
export async function exchangeCode(provider, { code, baseUrl, fetchImpl = fetch }) {
  let res;
  try {
    res = await fetchImpl(provider.tokenUrl, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: provider.clientId,
        client_secret: provider.clientSecret,
        code,
        redirect_uri: redirectUriFor(provider, baseUrl),
        grant_type: "authorization_code",
      }),
    });
  } catch (err) {
    return { ok: false, error: `network: ${err?.message ?? String(err)}` };
  }
  if (!res.ok) {
    let body = "";
    try {
      body = (await res.text()).slice(0, 300);
    } catch {
      /* the status code is the signal, the body is a nicety */
    }
    return { ok: false, error: `${provider.id} token ${res.status}: ${body}` };
  }
  let json;
  try {
    json = await res.json();
  } catch (err) {
    return { ok: false, error: `${provider.id} token response was not JSON: ${err?.message ?? String(err)}` };
  }
  if (!json.access_token) return { ok: false, error: `${provider.id} token response had no access_token` };
  return { ok: true, accessToken: json.access_token };
}

/** Fetch the verified email off the userinfo endpoint. Both providers put it
 * at the same `email` key when the `openid email` scope is granted, which is
 * exactly why the scope is requested and not left to a default. An
 * unverified email (rare, but Google exposes the flag) is treated as absent:
 * an OAuth login should be at least as trustworthy as clicking a mailed
 * link, not less. */
export async function fetchVerifiedEmail(provider, { accessToken, fetchImpl = fetch }) {
  let res;
  try {
    res = await fetchImpl(provider.userinfoUrl, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
  } catch (err) {
    return { ok: false, error: `network: ${err?.message ?? String(err)}` };
  }
  if (!res.ok) return { ok: false, error: `${provider.id} userinfo ${res.status}` };
  let json;
  try {
    json = await res.json();
  } catch (err) {
    return { ok: false, error: `${provider.id} userinfo response was not JSON: ${err?.message ?? String(err)}` };
  }
  const email = String(json.email ?? "").trim();
  if (!email) return { ok: false, error: `${provider.id} did not return an email` };
  // Google's field is `email_verified` (boolean); Microsoft's OIDC userinfo
  // does not expose a verification flag at all and is treated as verified by
  // definition (Microsoft will not issue the claim otherwise). Absent means
  // trust the provider rather than reject a provider we did not check for.
  if (json.email_verified === false) return { ok: false, error: `${provider.id} email is not verified` };
  return { ok: true, email };
}
